"""
SolNeutral — Backend API Server
=================================
Product:  SolNeutral
Stack:    Python Flask + Flask-CORS
Role:     Serves vault stats, PnL data, rebalance events,
          and user balances to the Next.js frontend dashboard.

Endpoints:
  GET  /                          Health check
  GET  /api/vault/stats           Overall vault performance metrics
  GET  /api/vault/apy             Current APY and funding rate
  GET  /api/vault/pnl             Hourly PnL history (last 7 days)
  GET  /api/vault/rebalances      Rebalance event log
  GET  /api/vault/funding-rates   Funding rate history
  GET  /api/user/<wallet>/balance User balance + accrued yield
  POST /api/user/deposit          Simulate a deposit
  POST /api/user/withdraw         Simulate a withdrawal request
  GET  /api/risk                  Live risk metrics

Run:
  python app.py

Author: SolNeutral Team
"""

from flask import Flask, jsonify, request
from flask_cors import CORS
from dotenv import load_dotenv
import json
import os
import csv
import random
from datetime import datetime, timedelta

load_dotenv()

app = Flask(__name__)
CORS(app, origins=[
    "http://localhost:3000",
    "https://solneutral-vault.vercel.app",
    "https://solneutral-vault-production.up.railway.app",
    "*"
])  # Allow Next.js frontend on any port to call this API

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────

PORT             = int(os.getenv("PORT", 5000))
DEBUG            = os.getenv("DEBUG", "true").lower() == "true"

# Path to simulation outputs (generated by simulate_trades.py)
BASE_DIR         = os.path.dirname(os.path.abspath(__file__))
SUMMARY_PATH = os.path.join(BASE_DIR, "solneutral_summary.json")
CSV_PATH     = os.path.join(BASE_DIR, "solneutral_simulation.csv")

# In-memory user deposit store (replaced by on-chain data post-launch)
# Structure: { wallet_address: { deposited, timestamp, shares } }
USER_DEPOSITS    = {}

# Vault total deposit tracking
VAULT_TVL        = 10_000.0   # Starts with our simulation seed capital
LOCK_PERIOD_DAYS = 90         # 3-month rolling lock


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def load_summary() -> dict:
    """Load the latest simulation summary JSON."""
    try:
        with open(SUMMARY_PATH, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {"error": "Summary not found. Run simulate_trades.py first."}
    except json.JSONDecodeError:
        return {"error": "Summary file is corrupted."}


def load_csv_rows(limit: int = 168) -> list:
    """
    Load hourly simulation CSV rows.
    Default limit = 168 hours (7 days) for PnL chart.
    """
    rows = []
    try:
        with open(CSV_PATH, "r") as f:
            reader = csv.DictReader(f)
            all_rows = list(reader)
            # Return most recent `limit` rows
            rows = all_rows[-limit:] if len(all_rows) > limit else all_rows
    except FileNotFoundError:
        pass
    return rows


def calculate_user_yield(deposit_usdc: float,
                          deposit_time: datetime,
                          net_apy_pct: float) -> dict:
    """
    Calculate accrued yield for a user based on their deposit,
    time in vault, and current net APY.
    """
    now          = datetime.now()
    days_in_vault = (now - deposit_time).total_seconds() / 86400
    daily_rate   = net_apy_pct / 100 / 365
    accrued      = deposit_usdc * daily_rate * days_in_vault
    unlock_date  = deposit_time + timedelta(days=LOCK_PERIOD_DAYS)
    locked       = now < unlock_date

    return {
        "deposit_usdc":    round(deposit_usdc, 2),
        "accrued_yield":   round(accrued, 4),
        "current_value":   round(deposit_usdc + accrued, 4),
        "days_in_vault":   round(days_in_vault, 1),
        "days_remaining":  max(0, round((unlock_date - now).days, 0)),
        "unlock_date":     unlock_date.isoformat(),
        "is_locked":       locked,
        "apy_applied_pct": round(net_apy_pct, 2),
    }


def format_response(data: dict, status: int = 200) -> tuple:
    """Standard API response wrapper."""
    return jsonify({
        "success": status == 200,
        "timestamp": datetime.now().isoformat(),
        "data": data,
    }), status


def error_response(message: str, status: int = 400) -> tuple:
    """Standard error response."""
    return jsonify({
        "success": False,
        "timestamp": datetime.now().isoformat(),
        "error": message,
    }), status


# ─────────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────────

@app.route("/", methods=["GET"])
def health_check():
    """Health check — confirms API is running."""
    return format_response({
        "product":  "SolNeutral",
        "version":  "1.0.0",
        "status":   "online",
        "network":  "Solana Devnet",
        "protocol": "Drift Protocol",
        "message":  "SolNeutral API is running. Delta-neutral vault active.",
    })


# ── VAULT ENDPOINTS ──────────────────────────

@app.route("/api/vault/stats", methods=["GET"])
def vault_stats():
    """
    Overall vault performance metrics.
    Used by: Dashboard page header, Strategy page.
    """
    summary = load_summary()
    if "error" in summary:
        return error_response(summary["error"], 503)

    perf = summary.get("performance", {})
    risk = summary.get("risk", {})
    sim  = summary.get("simulation", {})

    return format_response({
        "vault_name":          "SolNeutral",
        "strategy":            "Delta-Neutral (Spot + Perp)",
        "protocol":            "Drift Protocol",
        "chain":               "Solana",
        "tvl_usdc":            round(VAULT_TVL + sum(
                                   d["deposited"] for d in USER_DEPOSITS.values()
                               ), 2),
        "gross_apy_pct":       perf.get("gross_apy_pct", 0),
        "net_apy_pct":         perf.get("net_apy_pct", 0),
        "target_apy_pct":      perf.get("target_apy_pct", 10),
        "target_met":          perf.get("target_met", False),
        "gross_profit_usdc":   perf.get("gross_profit_usdc", 0),
        "net_profit_usdc":     perf.get("net_profit_usdc", 0),
        "total_fees_usdc":     perf.get("total_fees_usdc", 0),
        "max_drawdown_pct":    risk.get("max_drawdown_pct", 0),
        "sharpe_ratio":        risk.get("sharpe_ratio", 0),
        "rebalance_count":     risk.get("rebalance_count", 0),
        "simulation_days":     sim.get("days", 90),
        "lock_period_days":    LOCK_PERIOD_DAYS,
        "performance_fee_pct": 20,
        "last_updated":        summary.get("generated", datetime.now().isoformat()),
    })


@app.route("/api/vault/apy", methods=["GET"])
def vault_apy():
    """
    Current APY and live funding rate snapshot.
    Used by: Home page hero, Dashboard APY card.
    """
    summary = load_summary()
    if "error" in summary:
        return error_response(summary["error"], 503)

    fund = summary.get("funding", {})
    perf = summary.get("performance", {})

    avg_hourly = fund.get("avg_hourly_rate_pct", 0.004)
    projected_daily_apy = avg_hourly * 24
    projected_annual_apy = projected_daily_apy * 365

    return format_response({
        "net_apy_pct":              perf.get("net_apy_pct", 0),
        "gross_apy_pct":            perf.get("gross_apy_pct", 0),
        "current_hourly_rate_pct":  round(avg_hourly, 4),
        "projected_daily_pct":      round(projected_daily_apy, 4),
        "projected_annual_pct":     round(projected_annual_apy, 2),
        "positive_hours_pct":       fund.get("positive_funding_hours_pct", 0),
        "best_hourly_pct":          fund.get("max_hourly_rate_pct", 0),
        "worst_hourly_pct":         fund.get("min_hourly_rate_pct", 0),
        "funding_source":           "SOL-PERP short on Drift Protocol",
    })


@app.route("/api/vault/pnl", methods=["GET"])
def vault_pnl():
    """
    Hourly PnL history for chart rendering.
    Query params:
      ?hours=168   (default 168 = last 7 days)
      ?hours=720   (last 30 days)
      ?hours=2160  (full 90 days)
    Used by: Dashboard PnL chart.
    """
    hours = request.args.get("hours", 168, type=int)
    hours = min(hours, 2160)  # Cap at 90 days

    rows = load_csv_rows(limit=hours)

    if not rows:
        return error_response("PnL data not found. Run simulate_trades.py first.", 503)

    # Format for chart consumption
    chart_data = []
    for row in rows:
        chart_data.append({
            "timestamp":        row.get("Timestamp", ""),
            "vault_usdc":       float(row.get("Vault_USDC", 0)),
            "funding_earned":   float(row.get("Funding_Earned_USDC", 0)),
            "cumulative_yield": float(row.get("Cumulative_Funding_USDC", 0)),
            "drawdown_pct":     float(row.get("Drawdown_Pct", 0)),
        })

    return format_response({
        "hours_returned": len(chart_data),
        "chart_data":     chart_data,
    })


@app.route("/api/vault/rebalances", methods=["GET"])
def vault_rebalances():
    """
    Rebalance event log.
    Used by: Dashboard rebalance timeline.
    """
    summary = load_summary()
    risk    = summary.get("risk", {})
    count   = risk.get("rebalance_count", 269)

    # Generate rebalance event log from simulation period
    # (In production this comes from on-chain transaction logs)
    events  = []
    base    = datetime.now() - timedelta(days=90)

    for i in range(min(count, 50)):   # Return last 50 events max
        event_time = base + timedelta(hours=i * 8)
        events.append({
            "event_id":     i + 1,
            "timestamp":    event_time.isoformat(),
            "type":         "scheduled" if i % 5 != 0 else "threshold",
            "trigger":      "8h interval" if i % 5 != 0 else "delta drift > 2%",
            "spot_adj_pct": round(random.uniform(0.1, 2.5), 2),
            "perp_adj_pct": round(random.uniform(0.1, 2.5), 2),
            "cost_usdc":    round(random.uniform(0.005, 0.05), 4),
            "status":       "completed",
        })

    return format_response({
        "total_rebalances": count,
        "events_returned":  len(events),
        "rebalance_events": events,
    })


@app.route("/api/vault/funding-rates", methods=["GET"])
def funding_rates():
    """
    Recent funding rate history.
    Used by: Strategy page chart.
    """
    hours = request.args.get("hours", 72, type=int)
    rows  = load_csv_rows(limit=hours)

    rates = []
    for row in rows:
        rates.append({
            "timestamp":    row.get("Timestamp", ""),
            "rate_pct":     float(row.get("Funding_Rate", 0)) * 100,
            "earned_usdc":  float(row.get("Funding_Earned_USDC", 0)),
        })

    return format_response({
        "market":         "SOL-PERP",
        "protocol":       "Drift Protocol",
        "hours_returned": len(rates),
        "rates":          rates,
    })


# ── USER ENDPOINTS ───────────────────────────

@app.route("/api/user/<wallet>/balance", methods=["GET"])
def user_balance(wallet: str):
    """
    Get a user's vault balance, accrued yield, and lock status.
    Used by: Dashboard user balance card, Deposit/Withdraw page.
    """
    if not wallet or len(wallet) < 32:
        return error_response("Invalid wallet address.")

    summary  = load_summary()
    net_apy  = summary.get("performance", {}).get("net_apy_pct", 14.81)

    if wallet not in USER_DEPOSITS:
        return format_response({
            "wallet":         wallet,
            "has_deposit":    False,
            "message":        "No deposit found for this wallet.",
            "vault_net_apy":  net_apy,
        })

    deposit      = USER_DEPOSITS[wallet]
    deposit_time = datetime.fromisoformat(deposit["timestamp"])
    yield_data   = calculate_user_yield(deposit["deposited"], deposit_time, net_apy)

    return format_response({
        "wallet":       wallet,
        "has_deposit":  True,
        "shares":       deposit.get("shares", 0),
        **yield_data,
        "vault_net_apy": net_apy,
    })


@app.route("/api/user/deposit", methods=["POST"])
def user_deposit():
    """
    Simulate a USDC deposit into the vault.
    Body: { "wallet": "...", "amount_usdc": 500 }
    Used by: Deposit page.
    Note: In production this triggers an on-chain transaction.
    """
    global VAULT_TVL

    body = request.get_json()
    if not body:
        return error_response("Request body is required.")

    wallet     = body.get("wallet", "").strip()
    amount     = body.get("amount_usdc", 0)

    if not wallet or len(wallet) < 32:
        return error_response("Invalid wallet address.")
    if not isinstance(amount, (int, float)) or amount <= 0:
        return error_response("amount_usdc must be a positive number.")
    if amount < 10:
        return error_response("Minimum deposit is 10 USDC.")

    # Calculate shares (1:1 for simplicity in simulation)
    shares = amount

    # Store deposit
    USER_DEPOSITS[wallet] = {
        "deposited":  amount,
        "shares":     shares,
        "timestamp":  datetime.now().isoformat(),
    }

    VAULT_TVL += amount

    return format_response({
        "wallet":       wallet,
        "deposited":    amount,
        "shares":       shares,
        "unlock_date":  (datetime.now() + timedelta(days=LOCK_PERIOD_DAYS)).isoformat(),
        "lock_days":    LOCK_PERIOD_DAYS,
        "vault_tvl":    round(VAULT_TVL, 2),
        "message":      (f"Successfully deposited ${amount:.2f} USDC into SolNeutral. "
                         f"Locked for {LOCK_PERIOD_DAYS} days."),
        "tx_note":      "Simulation mode — no real transaction executed.",
    }, 201)


@app.route("/api/user/withdraw", methods=["POST"])
def user_withdraw():
    """
    Request a withdrawal from the vault.
    Body: { "wallet": "..." }
    Enforces 3-month lock period.
    Used by: Deposit/Withdraw page.
    """
    global VAULT_TVL

    body   = request.get_json()
    wallet = body.get("wallet", "").strip() if body else ""

    if not wallet or len(wallet) < 32:
        return error_response("Invalid wallet address.")

    if wallet not in USER_DEPOSITS:
        return error_response("No deposit found for this wallet.")

    deposit      = USER_DEPOSITS[wallet]
    deposit_time = datetime.fromisoformat(deposit["timestamp"])
    unlock_date  = deposit_time + timedelta(days=LOCK_PERIOD_DAYS)
    now          = datetime.now()

    if now < unlock_date:
        days_left = (unlock_date - now).days
        return error_response(
            f"Vault is locked. {days_left} days remaining until unlock "
            f"on {unlock_date.strftime('%Y-%m-%d')}.",
            403
        )

    summary  = load_summary()
    net_apy  = summary.get("performance", {}).get("net_apy_pct", 14.81)
    yield_data = calculate_user_yield(deposit["deposited"], deposit_time, net_apy)
    payout   = yield_data["current_value"]

    VAULT_TVL -= deposit["deposited"]
    del USER_DEPOSITS[wallet]

    return format_response({
        "wallet":          wallet,
        "principal_usdc":  deposit["deposited"],
        "yield_earned":    yield_data["accrued_yield"],
        "total_payout":    round(payout, 2),
        "days_in_vault":   yield_data["days_in_vault"],
        "apy_applied":     net_apy,
        "message":         f"Withdrawal of ${payout:.2f} USDC processed successfully.",
        "tx_note":         "Simulation mode — no real transaction executed.",
    })


# ── RISK ENDPOINT ────────────────────────────

@app.route("/api/risk", methods=["GET"])
def risk_metrics():
    """
    Live risk dashboard metrics.
    Used by: Dashboard risk panel, Strategy page.
    """
    summary = load_summary()
    risk    = summary.get("risk", {})
    fund    = summary.get("funding", {})

    return format_response({
        "max_drawdown_pct":      risk.get("max_drawdown_pct", 0),
        "drawdown_limit_pct":    10.0,
        "drawdown_status":       (
            "safe" if risk.get("max_drawdown_pct", 0) < 5
            else "warning" if risk.get("max_drawdown_pct", 0) < 8
            else "critical"
        ),
        "sharpe_ratio":          risk.get("sharpe_ratio", 0),
        "rebalance_count":       risk.get("rebalance_count", 0),
        "positive_funding_pct":  fund.get("positive_funding_hours_pct", 0),
        "collateral_buffer_pct": 20.0,
        "max_position_pct":      25.0,
        "liquidation_risk":      "low",
        "strategy_status":       "active",
        "last_rebalance":        (datetime.now() - timedelta(hours=4)).isoformat(),
        "next_rebalance":        (datetime.now() + timedelta(hours=4)).isoformat(),
    })


# ─────────────────────────────────────────────
# ERROR HANDLERS
# ─────────────────────────────────────────────

@app.errorhandler(404)
def not_found(e):
    return error_response(f"Endpoint not found.", 404)


@app.errorhandler(405)
def method_not_allowed(e):
    return error_response("Method not allowed on this endpoint.", 405)


@app.errorhandler(500)
def server_error(e):
    return error_response("Internal server error.", 500)


# ─────────────────────────────────────────────
# STARTUP
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 58)
    print("   SOLNEUTRAL — BACKEND API SERVER")
    print("   Delta-Neutral Vault | Powered by Drift Protocol")
    print("=" * 58)
    print(f"\n   Starting on http://localhost:{PORT}")
    print(f"   Debug mode : {DEBUG}")
    print(f"\n   Endpoints:")
    print(f"   GET  /                        Health check")
    print(f"   GET  /api/vault/stats         Vault performance")
    print(f"   GET  /api/vault/apy           Current APY")
    print(f"   GET  /api/vault/pnl           PnL history")
    print(f"   GET  /api/vault/rebalances    Rebalance events")
    print(f"   GET  /api/vault/funding-rates Funding rate history")
    print(f"   GET  /api/user/<wallet>/balance  User balance")
    print(f"   POST /api/user/deposit        Simulate deposit")
    print(f"   POST /api/user/withdraw       Simulate withdrawal")
    print(f"   GET  /api/risk                Risk metrics")
    print(f"\n{'=' * 58}\n")

    app.run(host="0.0.0.0", port=PORT, debug=DEBUG)
